spring:
  application:
    name: toures-balon-usuario-categoria
server:
  port: 0
---

eureka:
  client:
  #  service-url: {"http://toures-balon-discovery:8761/eureka"}
    serviceUrl:
      defaultZone: "http://192.168.0.6:8761/eureka"
  instance:
    prefer-ip-address: true
spring:
  sleuth:
     sampler:
       probability: 1.0
   zipkin:
     base-url: http://192.168.0.6:9411/
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://172.17.0.5:3306/toures-balon-categoria
    username: root
    password: root
  profiles: 
    active:
    - dev
gema:
  kafka:
    producer:
      enabled: true
      bootstrap-server: htpp://192.168.0.6:29092
    consumer:
      enabled: true
      bootstrap-server: htpp://192.168.0.6:29092
      
dividing-factor: 1000
 
